export interface CASTER_INTERFACE {
  level_1: any,
  level_2: any,
  level_3: any,
  level_4: any,
  level_5: any,
  level_6: any,
  level_7: any,
  level_8: any,
  level_9: any,
  level_10: any,
  level_11: any,
  level_12: any,
  level_13: any,
  level_14: any,
  level_15: any,
  level_16: any,
  level_17: any,
  level_18: any,
  level_19: any,
  level_20: any,
}